- name: Update apt cache
  apt:
    update_cache: yes

- name: Create teacher user
  user:
    name: teacher
    shell: /bin/bash
    groups: sudo
    append: yes
    password: "{{ '12345678' | password_hash('sha512') }}"

- name: Create gradebook directory
  file:
    path: /home/student
    state: directory
    mode: '0755'

- name: Create gradebook file
  copy:
    dest: /home/student/gradebook
    content: "{{ gradebook_number }}\n"
    mode: '0644'
