[workers]
192.168.100.140 ansible_user=ansible ansible_password=12345678

[db]
192.168.100.38 ansible_user=ansible ansible_password=12345678

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
